export function buildAlertEmail(alerts, timestamp) {
    const alertsHtml = alerts
        .map(alert => {
            return `
            <div>
                <h3>${alert.type}</h3>
                <p>${alert.message}</p>
            </div>
        `;
        })
        .join('');


    return `
        <html>
        <body>

            <h1>
                GitHub Status Alert By Argus
            </h1>

            <p>
                Changes were detected on GitHub Status.
            </p>

            ${alertsHtml}

            <hr />
            <p> Generated By <a href="https://argusalert.tech/">Argus</a> </p>
            <p>
                Timestamp: ${timestamp}
            </p>

        </body>
        </html>
    `;
}


export function buildDemoEmail(data) {
    const subStatusesHtml = data.subStatus
        .map(component => ` <tr> <td style="padding: 8px; border: 1px solid #ddd;"> 
        ${component.name} </td> <td style="padding: 8px; border: 1px solid #ddd;"> 
        ${component.status} </td> </tr> `).join("");

    const incidentsHtml = data.activeIncidents.length > 0 ? data.activeIncidents
        .map(incident => ` <li> <strong>${incident.name}</strong> (${incident.impact}) </li> `).join("") : "<p>No current unresolved incidents.</p>";
    return ` 
        <html> 
        <body style=" font-family: Arial, sans-serif; max-width: 700px; margin: auto; padding: 20px; "> 
        
            <h1> 
                GitHub Status Demo Alert By Argus
            </h1> 
            <p> 
                This is a demonstration alert generated from the latest GitHub Status snapshot. 
            </p> 
            <hr /> 
            <h2>
                Main Status
            </h2> 
            <p> 
                <strong> ${data.mainStatus} </strong> 
            </p> 
            <hr /> 
            <h2>
                Component Statuses
            </h2>
            <table style=" width: 100%; border-collapse: collapse; " > 
                <thead> 
                    <tr> 
                    <th style=" padding: 8px; border: 1px solid #ddd; "> Component </th> 
                    <th style=" padding: 8px; border: 1px solid #ddd; "> Status </th> 
                    </tr> 
                </thead> 
            <tbody> 
                ${subStatusesHtml} 
            </tbody> 
            </table> 
            <hr /> 
            <h2>Unresolved Incidents</h2> 
            ${incidentsHtml} 
            <hr /> 
            <p> Generated By <a href="https://argusalert.tech/">Argus</a> </p> 
            <p> Timestamp: ${new Date().toLocaleString('en-US', { timeZone: 'Asia/Kolkata', timeZoneName: 'short' })} </p> 
        </body> 
        </html> 
        `;
}